version: '3.8'

services:
  bot:
    container_name: 'qbf_support_bot'
    build: .
    image: 'bots/qbf_support'
    volumes:
      - ./menu.xlsx:/opt/qbf_support_bot/menu.xlsx
    env_file: 'env'
    restart: always
